language: php

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="2.5.*"
    - SYMFONY_VERSION="2.6.*"

before_script:
    - COMPOSER_ROOT_VERSION=dev-master
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

script: phpunit --configuration phpunit.xml.dist --exclude-group ""

matrix:
    allow_failures:
        - php: hhvm-nightly

